const Icons = {
    avatar:require("./assets/image/icon_avatar.png"),
    asc:require("./assets/image/icon_asc.png"),
    desc:require("./assets/image/icon_desc.png"),
    disorder:require("./assets/image/icon_disorder.png"),
    add_green:require("./assets/image/icon_add_green.png"),
    back_black:require("./assets/image/icon_left_dark.png"),
    select_green:require("./assets/image/icon_bottom_dark.png"),
    cashier:require("./assets/image/icon_cashier.png"),
    rightArrow_gray:require("./assets/image/icon_right.png"),
    rightArrow_black:require("./assets/image/icon_right.png"),
    rightArrow_white:require("./assets/image/icon_right_white.png"),
    leftArrow_black:require("./assets/image/icon_left_dark.png"),
    leftArrow_white:require("./assets/image/icon_left_white.png"),
    list_open_detail:require("./assets/image/icon_list_open_detail.png"),
    list_off_detail:require("./assets/image/icon_list_off_detail.png"),
    public_search:require('./assets/image/icon_search_gray.png'),
    public_delete:require('./assets/image/icon_public_delete.png'),
    checkBox_green:require("./assets/image/icon_checkBox_green.png"),
    radio_gray:require("./assets/image/icon_radio_gray.png"),
    radio_green:require("./assets/image/icon_radio_green.png"),
    address:require("./assets/image/icon_address.png"),
    cartlist_boxcashreceived:require("./assets/image/icon_cartlist_boxcashreceived.png"),
    cartlist_boxcash:require("./assets/image/icon_cartlist_boxcash.png"),
    publick_loading:require("./assets/image/icon_publick_loading.gif"),
    radio_publick_printerloading:require("./assets/image/icon_publick_printerloading.gif"),
    search_blue:require("./assets/image/icon_search_select.png"),

  }
export { Icons }